### ISSUE TITLE
软件本身通讯的时候加密没有

### ISSUE THREAD

**Issue by charli2014** [d1sm/finalspeed#1]
大大，你好。我想问下fs本身通讯时，有没有加密。我主要先直接在服务器端开一个http代理，不通过ss。因为如果用ss的话，本地端需要两个软件，太麻烦。但是又怕fs没有加密，http传输容易被干扰。

**Comment by d1sm** [comment]
没有加密,有安全需求的的不要直接加速http,socks5这些明文协议.

**Comment by charli2014** [comment]
知道了，谢谢大大
