### ISSUE TITLE
iptables 配置被清空

### ISSUE THREAD

**Issue by jeff-teng** [d1sm/finalspeed#12]
每次启动都删我其他服务的 iptables 配置吗= =

**Comment by jeff-teng** [comment]
![17 s 89b n2t5kg him 97](https://cloud.githubusercontent.com/assets/5853474/12445250/2d77f250-bf9e-11e5-9e92-1ec779c890e2.jpg)

**Comment by ragnaroks** [comment]
这个是清空已有的FS的配置吧

**Comment by jeff-teng** [comment]
又看了一下，好像是在起 iptables 服务的时候覆盖了我 firewalld 的配置

**Comment by d1sm** [comment]
不会修改已有规则,fs的规则comment都带有fs标记.

**Comment by jeff-teng** [comment]
好的，辛苦了
