### ISSUE TITLE
客户端显示连接服务器成功，但浏览器还是连不上网

### ISSUE THREAD

**Issue by zhangchenchen** [d1sm/finalspeed#17]
日志显示：

> delay_udp 240ms 123.114.**.**_:59217
> delay_udp 240ms 123.114.__._**:59217
> delay_udp 242ms 123.114.**.***:59217

**Comment by zhangchenchen** [comment]
在论坛找到原因了，服务只绑定了一个IP。谢谢

**Comment by icecrack** [comment]
没看明白，能解释下么？

**Comment by zhangchenchen** [comment]
原因：.被加速的应用服务端绑定某个ip,造成fs服务端无法连接,应取消绑定,或将绑定ip修改为0.0.0.0.
详细信息[见此](http://www.d1sm.net/thread-36-1-1.html)
