### ISSUE TITLE
对Netflix没有加速效果

### ISSUE THREAD

**Issue by lichader** [d1sm/finalspeed#18]
不知道为什么对Netflix没有效果，但是youtube是有的。

在safari和chrome里都测试过了。

safari用的是silverlight插件
chrome应该是html5.

谢谢。

**Comment by fly9i** [comment]
因为netflix不在gfwlist里面？

**Comment by lichader** [comment]
@fly9i 这个不太确定。但是netflix的流量是肯定走的shadowsock的，否则我也打不开，因为它有地区限制。

**Comment by d1sm** [comment]
应该不是fs的问题,fs不会区分网站

**Comment by mahaoying** [comment]
@lichader fs不具有流量的区分能力，流量怎么走由你的本地代理规则、pac规则或者服务端决定。netflix的媒体服务器好像并不是netflix.com的域名。所以你可以试试开SS代理是否有加速效果或者分析下链接情况，加速媒体服务器。好比YouTube的图像服务器域名是ytimg.com一样，单纯代理youtube.com是不能加速ytimg.com的。
