### ISSUE TITLE
openwrt路由ss有没有效果

### ISSUE THREAD

**Issue by javenfeng** [d1sm/finalspeed#2]
以前我用锐速（DO）和Netspeeder(BWG)都跑不满宽带啊，这个真的可以90%吗？
我是在路由上使用ss客户端的，那么就没法在本地跑了吧？
路由的话，只在服务器端安装，本地不安装，会有效果吗？与net_speeder相比如何？
谢谢。

**Comment by d1sm** [comment]
必须装客户端,否则没任何效果.
