### ISSUE TITLE
linux 客户端后台运行

### ISSUE THREAD

**Issue by i-sync** [d1sm/finalspeed#25]
@zqhong 请问题这个命令sudo java -jar client.jar 怎么后台运行？以及有没有重启的方法？
我想把客户端运行在raspberry pi 2 上。
https://github.com/zqhong/finalspeed

**Comment by zqhong** [comment]
后台运行可以用下面这个：
`$ sudo nohup java -jar client.jar &`

重启？获取 pid 之后 kill 掉进程，再启动就好了。试试看把下面脚本保存为 restart.sh，跑跑看。

``` bash
#!/bin/bash

pid=$(ps -ef | grep client.jar | awk '$10 == "client.jar" { print $2 }')
kill $pid
sudo nohup java -jar client.jar &
```

**Comment by i-sync** [comment]
谢谢~
