### ISSUE TITLE
jvm参数导致不能启动客户端

### ISSUE THREAD

**Issue by fbi007130** [d1sm/finalspeed#33]
<img width="531" alt="2016-03-05 12 34 53" src="https://cloud.githubusercontent.com/assets/3862344/13545695/2144a06a-e2cf-11e5-84e0-4719669db91e.png">

**Comment by d1sm** [comment]
把bat文件里的Xmx参数改小

**Comment by fbi007130** [comment]
windows客户端目录里边貌似找不到有bat文件

**Comment by fbi007130** [comment]
今天重启就没事了。。。。奇怪
