### ISSUE TITLE
FS把服务器上所有端口都暴露给客户端了，无视防火墙？

### ISSUE THREAD

**Issue by losfair** [d1sm/finalspeed#34]
貌似FS Server把服务器上所有的端口，包括监听在127.0.0.1上的，都暴露给客户端了，而一些敏感端口是不能开放的，是不是不安全？

**Comment by d1sm** [comment]
待后续完善了,一般应用问题不大

**Comment by ghost** [comment]
是否可以在Finalspeed里面默认屏蔽例如3306等端口呢，这个端口比较敏感

**Comment by wwng2333** [comment]
为什么要把所有鸡蛋放在一个篮子里？
