### ISSUE TITLE
能否详细介绍下

### ISSUE THREAD

**Issue by chaclus** [d1sm/finalspeed#41]
很想了解，能否详细介绍下finalspeed，双边加速是怎么个原理。-_-

**Comment by lialosiu** [comment]
简单的说就是把原始的数据包封装起来，用自己
实现的协议发包，以适应天朝这种高丢包环境的网络
把封好的数据包传到目标机之后，再还原成原始数据包

2016年3月10日 17:31，"sticver" notifications@github.com写道：

**Comment by bluetib** [comment]
ss出去的都是加密数据，所以应该只是在外层包了一下。

很好奇的是，这个私有协议，是如果起到加速作用的。缓冲区？

我在使用过程中，感觉udp协议的数据包速度很快，墙应该不好处理。

**Comment by vainly** [comment]
finish
