### ISSUE TITLE
教程說明模糊

### ISSUE THREAD

**Issue by 1a57danc3** [d1sm/finalspeed#56]
ss端口为8989 这个指的是服务器还是客户端 ？另外finalspeed的本地端口走的协议是什么？

**Comment by realgtk** [comment]
教程写的已经很清楚了，只能怪你自己理解不深。
FS服务端不用设置，需要设置的都是FS客户端（FS客户端相当于一个新的SS代理服务器），8989是原SS的端口（如果你的SS端口是443，那这里就是443），本地端口2000是FS创建的端口，你的shadowsocks客户端可以连接原先的SS的IP:8989端口（这种情况是不加速的），或者连接127.0.0.1:2000端口（加速）。明白了没？

**Comment by 1a57danc3** [comment]
> 教程写的已经很清楚了，只能怪你自己理解不深。
> FS服务端不用设置，需要设置的都是FS客户端（FS客户端相当于一个新的SS代理服务器），8989是原SS的端口（如果你的SS端口是443，那这里就是443），本地端口2000是FS创建的端口，你的shadowsocks客户端可以连接原先的SS的IP:8989端口（这种情况是不加速的），或者连接127.0.0.1:2000端口（加速）。明白了没？
> 

thx
