### ISSUE TITLE
如何配合路由上的SS使用？

### ISSUE THREAD

**Issue by TheHooper** [d1sm/finalspeed#61]
有办法配合基于Linux的路由使用吗？有的话就太好了！！

**Comment by lersh** [comment]
我的方案是再买个树莓派2，在树莓派上跑finalspeed
然后路由器里的ss的代理地址指向树莓派

**Comment by hmmabc** [comment]
买个x86的mini机就行了，功耗最高8w，ss，fs可以都部署在上面。

**Comment by TheHooper** [comment]
很好的方案呀！但是小白求教x86如何代理路由的请求呀~~就是配置操作……

**Comment by hmmabc** [comment]
路由还是用路由器，这个mini机只做http/socks代理，若有兴趣，完全可以开启更多的服务，然后路由把端口映射进来就可以。

**Comment by TheHooper** [comment]
明白了，路由器设置转发规则，映射到mini机。这两种方案费用都不低额……不知道把java版的去界面后，丢在linux里跑可不可行。

**Comment by Enivel** [comment]
目前树莓派3完美运行. 速度比直接在macbook上跑gui版的客户端还要好

**Comment by flankcheung** [comment]
@Enivel  你的pi3 跑到什么系统？
