### ISSUE TITLE
如何在服务端指定网卡接口

### ISSUE THREAD

**Issue by StarDuster** [d1sm/finalspeed#8]
```
FinalSpeed server starting...
System Name: linux
Listen udp port: 150
Listen tcp port: 150
Network Interface List:
     venet0
     zt0
     ipsec0
  Pseudo-device that captures on all interfaces   any
     lo
Selected Network Interface:
     lo
```

自动选择到了 lo 让我很是无语

**Comment by d1sm** [comment]
修改一下网卡顺序.

**Comment by embeddedsecurity** [comment]
> ```
> FinalSpeed server starting...
> System Name: linux
> Listen udp port: 150
> Listen tcp port: 150
> Network Interface List:
>      venet0
>      zt0
>      ipsec0
>   Pseudo-device that captures on all interfaces   any
>      lo
> Selected Network Interface:
>      lo
> ```
> 
> 自动选择到了 lo 让我很是无语

你是怎么修改网卡顺序的？vps有几块网卡，如何判断哪块是和外网连接的网卡？热心人一生平安！
